# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Political_Compass_AI',
                'doc_host': 'https://RonTuretzky.github.io',
                'git_url': 'https://github.com/RonTuretzky/Political_Compass_AI',
                'lib_path': 'Political_Compass_AI'},
  'syms': {'Political_Compass_AI.core': {'Political_Compass_AI.core.foo': ('core.html#foo', 'Political_Compass_AI/core.py')}}}
