# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Political_Compass_AI',
                'doc_host': 'https://RonTuretzky.github.io',
                'git_url': 'https://github.com/RonTuretzky/Political_Compass_AI',
                'lib_path': 'Political_Compass_AI'},
  'syms': { 'Political_Compass_AI.alignment_count': { 'Political_Compass_AI.alignment_count.alignment_count': ( 'count_alignments.html#alignment_count',
                                                                                                                'Political_Compass_AI/alignment_count.py')},
            'Political_Compass_AI.make_balanced_db': { 'Political_Compass_AI.make_balanced_db.make_balanced_db': ( 'make_balanced_db.html#make_balanced_db',
                                                                                                                   'Political_Compass_AI/make_balanced_db.py')},
            'Political_Compass_AI.merge_data_bases': { 'Political_Compass_AI.merge_data_bases.merge_data_bases': ( 'merge_to_one.html#merge_data_bases',
                                                                                                                   'Political_Compass_AI/merge_data_bases.py')},
            'Political_Compass_AI.parse_for_dupes': { 'Political_Compass_AI.parse_for_dupes.parse_for_dupes': ( 'db_stat_parser.html#parse_for_dupes',
                                                                                                                'Political_Compass_AI/parse_for_dupes.py')}}}
