# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/count_alignments.ipynb.

# %% auto 0
__all__ = ['alignment_count']

# %% ../nbs/count_alignments.ipynb 0
from fastcore.script import call_parse
from ast import literal_eval as make_tuple

@call_parse
def alignment_count(
            path:str # dn path to run alignment distribution

):
    db = open(path, "r")
    #TODO Add all alignments
    alignments = {
        "Libertarian Left": 0,
        "Libertarian Right": 0,
        "Authoritarian Left": 0,
        "Authoritarian Right": 0,
    }
    for line in db:
        opinion, text = make_tuple(line)
        alignments[opinion] += 1
    print(alignments)

