# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/make_balanced_db.ipynb.

# %% auto 0
__all__ = ['make_balanced_db']

# %% ../nbs/make_balanced_db.ipynb 0
from fastcore.script import call_parse
@call_parse()
def make_balanced_db(
        db_path:str # Path to db to balance
        ,newdatabase:str # Path for merged database
        ,count:str # Number of each alignment
):
    file1 = open(db_path, "r")
    writeToFile = open(newdatabase, "w")
    #TODO Update for all alignments
    c = [int(count)]*4
    mapping = {
        "Libertarian Left": 0,
        "Libertarian Right": 1,
        "Authoritarian Left": 2,
        "Authoritarian Right": 3,
    }
    for line in file1:
        opinion, text = make_tuple(line)
        index = mapping[opinion]
        if (c[index] > 0):
            c[index] -= 1
            writeToFile.write(line)

