# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/merge_to_one.ipynb.

# %% auto 0
__all__ = ['merge_data_bases']

# %% ../nbs/merge_to_one.ipynb 0
from fastcore.script import call_parse
@call_parse
def merge_data_bases(
        path1:str # Path to first database to merge
        ,path2:str # Path for second database to merge
        ,newdatabase:str # Path for merged database
):
    file_1 = open(path1, "r")
    file_2 = open(path2, "r")
    newDBFile = open(newdatabase,"a")
    newDBlst = []
    files = [file_1,file_2]
    for file in files:
        for line in file:
            if line not in newDBlst:
                newDBlst.append(line)
    for row in newDBlst:
        newDBFile.write(row)

