# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Db_Utils/db_stat_parser.ipynb.

# %% auto 0
__all__ = ['parse_for_dupes']

# %% ../nbs/Db_Utils/db_stat_parser.ipynb 0
from fastcore.script import call_parse
from ast import literal_eval as make_tuple
@call_parse()
def parse_for_dupes(
            db_path1:str # Path to db1 to parse
            ,db_path2:str # Path to db2 to parse

):
    # This code checks duplicates between two databases
    with open(db_path1, "r") as file1:
    # Read the lines in the first file into a set
        file1_lines = set(file1.readlines())
        print(len(file1_lines))

# Open the second file
    with open(db_path2, "r") as file2:
        # Read the lines in the second file into a set
        file2_lines = set(file2.readlines())
        print(len(file2_lines))
    duplicate_lines = file1_lines.intersection(file2_lines)
    print(len(duplicate_lines))
